### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by ChoAhChoAh** [ipk2015/RN-Resource-ipk#1]
RN之Android:原生界面与React界面的相互调用及数据传递.md
这篇文章里的
public static ArrayBlockingQueue<String> myBlockingQueue = new ArrayBlockingQueue<String>(1);

@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(resultCode == RESULT_OK && requestCode == 100){
            String result = data.getStringExtra("result");
            if (！TextUtils.isEmpty(result)){
                    MyConstants.myBlockingQueue.add(result);
                } else {
                    MyConstants.myBlockingQueue.add("无数据传回");
                }
            }
        }else{
            MyConstants.myBlockingQueue.add("没有");
        }
    }
这段代码中的MyConstants是哪里的，这个文章的源码有没有例子额，看这个教程感觉还是有点迷糊

**Comment by ipk2015** [comment]
@ChoAhChoAh 呃，这个MyConstans没什么用，只是个放置一些常量或者常用变量的类。你看MyConstants.myBlockingQueue只是为了用myBlockingQueue这个静态变量而已，自己用的时候可以随便放的。
没放例子主要是觉得RN工程需要放的东西比较多，实际有用的要自己写的代码没多少。
